[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[[plugins]]
  package = "@netlify/build-plugin-vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval';"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Cache-Control = "public, max-age=31536000, immutable"

[functions]
  node_bundler = "esbuild"