[build]
  command = "npm install -g @netlify/build-plugin-vite && npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16.20.2"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_NODE_VERSION = "16.20.2"

[[plugins]]
  package = "@netlify/build-plugin-vite"

[build.processing]
  skip_processing = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"